name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Adjust this to match the branch you want to trigger this workflow.

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{sanjay }}
          password: ${{dckr_pat_pnI031JhYvkH4dk8bmFz-lwMBG4 }}

      - name: Build and push Docker Image 1
        run: |
          docker build . -f Dockerfile -t sanjayraj/image1:latest --build-arg CONFIG=configuration1
          docker push sanjayraj/image1:latest

      - name: Build and push Docker Image 2
        run: |
          docker build . -f Dockerfile -t sanjayraj/image2:latest --build-arg CONFIG=configuration2
          docker push sanjayraj/image2:latest

      - name: Build and push Docker Image 3
        run: |
          docker build . -f Dockerfile -t sanjayraj/image3:latest --build-arg CONFIG=configuration3
          docker push sanjayraj/image3:latest

      # Add this new step to delete the first Docker image
      - name: Delete the First Docker Image
        run: |
          echo "Deleting the first Docker image from Docker Hub..."
          bash delete_first_image.sh
        env:
          DOCKER_USERNAME: ${{sanjayraj}}
          DOCKER_PASSWORD: ${{sanjay6287}}
